In [1]:
import torch

In [2]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]]) # shape [2, 3]

In [3]:
print(f"x: {x} \n{x.shape}")

x: tensor([[1, 2, 3],
        [4, 5, 6]]) 
torch.Size([2, 3])


In [4]:
print("reshape: change layout without changing data")
print(f"reshaped: {x.reshape(3,2)}")

reshape: change layout without changing data
reshaped: tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [5]:
print("transpose swaps dims 0 and 1")
print(f"transposed: {x.transpose(0,1)}")

transpose swaps dims 0 and 1
transposed: tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [6]:
batched = x.unsqueeze(0)
squeezed = batched.squeeze(0)
print(f"x: \n{x},  \nshape={x.shape}")
print(f"\nunsqueeze -> batched: add dim\n{batched}, \nshape = {batched.shape}")
print(f"\nsqueeze -> remove dim: \n{squeezed}, \nshape = {squeezed.shape}")

x: 
tensor([[1, 2, 3],
        [4, 5, 6]]),  
shape=torch.Size([2, 3])

unsqueeze -> batched: add dim
tensor([[[1, 2, 3],
         [4, 5, 6]]]), 
shape = torch.Size([1, 2, 3])

squeeze -> remove dim: 
tensor([[1, 2, 3],
        [4, 5, 6]]), 
shape = torch.Size([2, 3])


In [7]:
print(f"x: {x}")
print(f"row1: {x[1]}")
print(f"col2: {x[:, 2]}")
print(f"sub: {x[0:2, 1:3]}")
print(f"mask: {x[x > 2]} -> bool masking flatten to 1D")

x: tensor([[1, 2, 3],
        [4, 5, 6]])
row1: tensor([4, 5, 6])
col2: tensor([3, 6])
sub: tensor([[2, 3],
        [5, 6]])
mask: tensor([3, 4, 5, 6]) -> bool masking flatten to 1D


In [8]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print("a=", a)
print("b=", b)
print(f"cat_dim0 = {torch.cat((a, b), dim=0)}")
print(f"cat_dim1 = {torch.cat((a, b), dim=1)}")
print(f"stack_dim0 = {torch.stack((a, b), dim=0)}")
print(f"stack_dim1 = {torch.stack((a, b), dim=1)}")

a= tensor([[1, 2],
        [3, 4]])
b= tensor([[5, 6],
        [7, 8]])
cat_dim0 = tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
cat_dim1 = tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
stack_dim0 = tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
stack_dim1 = tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [9]:
row = torch.tensor([1, 2, 3])
col = torch.tensor([[10], [20]])

print(f"row: {row}\ncol: {col}")

print(f"row + col: {row + col}")

row: tensor([1, 2, 3])
col: tensor([[10],
        [20]])
row + col: tensor([[11, 12, 13],
        [21, 22, 23]])


In [10]:
W = torch.randn(3, 4)
v = torch.randn(1, 3)

product = torch.matmul(v, W)

print(f"\nW: {W}\n{W.shape}")
print(f"v: {v}\n{v.shape}")
print(f"torch.matmul(v, W): {product}")

v = v[0]
product = torch.matmul(v, W)

print(f"\nW: {W}\n{W.shape}")
print(f"v: {v}\n{v.shape}")
print(f"torch.matmul(v, W): {product}")


W: tensor([[-1.4545,  1.0154, -0.1514,  0.9779],
        [-0.3633, -1.0481, -0.4194,  0.0843],
        [-1.3186, -0.0463, -1.4592, -0.7041]])
torch.Size([3, 4])
v: tensor([[ 1.6589, -0.1125, -0.3080]])
torch.Size([1, 3])
torch.matmul(v, W): tensor([[-1.9659,  1.8166,  0.2454,  1.8296]])

W: tensor([[-1.4545,  1.0154, -0.1514,  0.9779],
        [-0.3633, -1.0481, -0.4194,  0.0843],
        [-1.3186, -0.0463, -1.4592, -0.7041]])
torch.Size([3, 4])
v: tensor([ 1.6589, -0.1125, -0.3080])
torch.Size([3])
torch.matmul(v, W): tensor([-1.9659,  1.8166,  0.2454,  1.8296])
